---
version: 2
plan:
  project-key: SPECS
  key: STASH
  name: bamboo specs yaml

stages:
  - stage 1:
    - Ndepend
    
Ndepend:
  tasks:
    - script:
        interpreter: powershell
        scripts:
          - ${bamboo.build.working.directory}\Devops\AutoInstall
  requirements:
    - Master-Ndepend
...