---
project:
  key: SPECS
  plan:
    key: STASH
    name: bamboo specs yaml
stages:
  - jobs:
      - scripts:
          - echo 'testing3 artifact'
        artifacts:
          - name: test file
            path: test.txt
...